# Generated by Django 3.0.2 on 2020-03-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='type_symptom',
            field=models.CharField(choices=[('U', 'Incomum'), ('C', 'Comum')], max_length=1, verbose_name='Tipo de Sintoma'),
        ),
    ]
