# Generated by Django 3.0.3 on 2020-03-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersymptoms',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
