# Generated by Django 3.0.2 on 2020-03-28 07:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('characteristics', models.ManyToManyField(related_name='recommendations_set', to='base.Characteristic', verbose_name='Caracteristicas')),
                ('diseases', models.ManyToManyField(related_name='recommendations_set', to='base.Disease', verbose_name='Doenças')),
                ('symptoms', models.ManyToManyField(related_name='recommendations_set', to='base.Symptom', verbose_name='Sintomas')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
            },
        ),
        migrations.RemoveField(
            model_name='symptomoccurrence',
            name='date',
        ),
        migrations.RemoveField(
            model_name='symptomoccurrence',
            name='status',
        ),
        migrations.AddField(
            model_name='symptomoccurrence',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Termino do Sintoma'),
        ),
        migrations.AddField(
            model_name='symptomoccurrence',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Inicio do Sintoma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='symptoms',
            field=models.ManyToManyField(through='base.SymptomOccurrence', to='base.Symptom', verbose_name='Sintomas'),
        ),
        migrations.DeleteModel(
            name='UserSymptoms',
        ),
    ]
