# Generated by Django 3.0.2 on 2020-03-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200328_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='texto',
            new_name='text',
        ),
    ]
