# Generated by Django 3.0.2 on 2020-03-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200328_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='characteristics',
            field=models.ManyToManyField(blank=True, related_name='recommendations_set', to='base.Characteristic', verbose_name='Caracteristicas'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='recommendations_set', to='base.Disease', verbose_name='Doenças'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='recommendations_set', to='base.Symptom', verbose_name='Sintomas'),
        ),
    ]
