# Generated by Django 3.0.2 on 2020-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200328_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='chars',
            field=models.ManyToManyField(related_name='userapp_set', to='base.Characteristic', verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='diseases',
            field=models.ManyToManyField(related_name='userapp_set', to='base.Disease', verbose_name='Doenças'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='type_symptom',
            field=models.CharField(choices=[('U', 'Incomum'), ('C', 'Comum'), ('R', 'Crítico')], max_length=1, verbose_name='Tipo de Sintoma'),
        ),
    ]
